import pandas as pd

df = pd.read_csv('data.csv')

# new_df=df.dropna()

# print(new_df.to_string())

# new_df=df.fillna()
# print(df.isnull())
# print(df.isna())
# print(df.describe())
# print(df.shape)
# print(df.columns)
# print(df.dtypes)
# print(df.index)
# print(df["name"].isna())
# print(df.isnull().sum())
# print(df.isnull().mean()*100)
# print(df[df.isnull().any(axis=1)])
# print(new_df)
# df['age'] = df['age'].fillna(df['age'].median())
# print( df['age'].fillna(df['age'].median()))
# df["age"].fillna(df["age"].median())
# print(df["age"])
# print(df["city"].fillna(df["city"].mode()[0]))
# # print(df["age"].fillna(df["age"].median())[0])
# df["age"]=pd.to_numeric(df["age"], errors="coerce")
# df["age"] = df["age"].fillna(df["age"].median())
# print(df["age"])
# print(df["city"].fillna(df["city"].mode()[0]))
# print(df.duplicated().sum())
# df.drop_duplicates()
# df.drop_duplicates(subset=["email"])